apiVersion: v1
kind: PersistentVolumeClaim #Estou a criar um PVC para o postgres para que os dados sejam persistentes.
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce #Estou a usar o modo ReadWriteOnce porque só quero que um pod possa escrever no volume, visto só haver 1 replica. Although, se calhar um ReadWriteMany seria melhor para um ambiente de produção?
  resources:
    requests:
      storage: 1Gi  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: postgres
        image: postgres:17
        ports:
          - containerPort: 5432
        envFrom:
          - configMapRef:
              name: db-config
        volumeMounts: 
          - name: postgres-data
            mountPath: /var/lib/postgresql/data 
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc #Estou a referenciar o PVC que criei anteriormente.
---
apiVersion: v1
kind: Service #Estou a criar um service para o postgres para que o odoo possa comunicar com a base de dados.
metadata:
  name: postgres-service
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: database