apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config 
data: #Estou a usar o data para definir as variáveis de ambiente que o postgres precisa para correr, mas podiam existir dentro do db.yaml.
  POSTGRES_PASSWORD: odoo
  POSTGRES_USER: odoo
  POSTGRES_DB: postgres
  